import Head from 'next/head'
import { useEffect, useState } from 'react'
import Main from '../components/main'
import ProductsList from '../components/products/ProductsList'
import Dropdown from '../components/sidebar/Dropdown'
import Sidebar from '../components/sidebar/Sidebar'
import { categorizeData } from '../utils/categorizeData'
import { filterData } from '../utils/filterData'

export default function Home({ data }) {
  //all data catagorized
  const [categorizedData, allCities, allStates] = categorizeData(data)
  const [filters, setFilters] = useState([null, null, null])
  let [[fProducts, fCities, fStates], setFData] = useState([categorizedData, allCities, allStates]);
  useEffect(() => {
    setFData(filterData(categorizedData, allCities, allStates, filters))
  }, [filters])


  //console.log(filters)
  //generate product lists 
  console.log(categorizedData)
  //console.log(fProducts, fCities, fStates)
  let lists = []
  for (const [productName, products] of fProducts.entries()) {
    lists.push(<ProductsList key={productName} productName={productName} products={products.products} />)
  }

  return (
    <div className='bg-gray-800 min-h-screen max-w-screen flex flex-col  sm:flex-row '  >
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar >
        <Dropdown title="Products" index={0} select={setFilters} options={[...categorizedData.keys()]} />
        <Dropdown title="State" index={1} select={setFilters} options={[...fStates]} />
        <Dropdown title="City" index={2} select={setFilters} options={[...fCities]} />
      </Sidebar>
      <Main >
        {lists}
      </Main>

    </ div>
  )
}

export async function getStaticProps() {
  const res = await fetch('https://assessment-edvora.herokuapp.com/')
  const data = await res.json()
  return {
    props: {
      data: data
    },
    revalidate: 10
  }
}